### PR TITLE
Remove setuptools as runtime requirement

### PR DESCRIPTION
**Pull request by maresb**
Setuptools was added in https://github.com/conda-forge/plotly-feedstock/commit/9aeba4987669db29659e4db2e2ad0e0ad1c59c11 to fix missing pkg_resources. But pkg_resources was [removed in v3.3.0](https://github.com/plotly/plotly.py/blob/c1166729192e5278fb18c5165cd1b88d9dd5c07c/CHANGELOG.md#fixed-36).

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@chohner, @moorepants, and @ocefpaf, ready for review.

I was concerned about the removal of setuptools potentially breaking something in some subdependency, so now I test-import all the packages listed in setup.py.

**Review by chohner — APPROVED** [review]
lgtm!

**Comment by ocefpaf** [comment]
Thanks!

**Pull request merged**
