### PR TITLE
Install the Plotly JupyterLab extension alongside Plotly.py

### LINKED ISSUE #84: Enable Jupyterlab support
Issue:

I installed this package "conda install -c conda-forge plotly" but there is no integration with JupyterLab. No figures display when Python based plotly code is executed. See:

95098205-aac72500-072e-11eb-9750-b8366fb1a611

I think that some extra commands are needed:

https://plotly.com/python/getting-started/#jupyterlab-support-python-35

I think it would be a good idea to have this package automatically install the JupyterLab extension so things just work for the user.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/moorepants/miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
altair                    4.1.0                      py_1    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               20.1.0           py37h8f50634_1    conda-forge
astroid                   2.4.2            py37hc8dfbb8_0    conda-forge
asv                       0.4.2            py37h3340039_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
bibtexparser              1.1.0                      py_0    conda-forge
bicycleparameters         1.0.0                      py_2    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.20.1               he1b5a44_0    conda-forge
bokeh                     2.2.1            py37hc8dfbb8_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
bqplot                    0.12.17            pyh9f0ad1d_0    conda-forge
brotli                    1.0.9                he1b5a44_1    conda-forge
brotli-python             1.0.9            py37hb892b2f_1    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
brunsli                   0.1                  he1b5a44_0    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.3           py37h2b28604_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1007    conda-forge
charls                    2.1.0                he1b5a44_2    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cmarkgfm                  0.4.2            py37h516909a_2    conda-forge
colorama                  0.4.3                      py_0    conda-forge
conda                     4.8.5            py37hc8dfbb8_1    conda-forge
conda-build               3.20.3           py37hc8dfbb8_0    conda-forge
conda-package-handling    1.7.0            py37h8f50634_5    conda-forge
control                   0.8.3                    py37_1    conda-forge
coverage                  5.3              py37h8f50634_0    conda-forge
cryptography              3.1.1            py37hb09aad4_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cyipopt                   0.2.0            py37h03ebfcd_0    conda-forge
cython                    0.29.21          py37h3340039_0    conda-forge
cytoolz                   0.11.0           py37h8f50634_0    conda-forge
dash                      1.16.2             pyh9f0ad1d_0    conda-forge
dash-bootstrap-components 0.10.7             pyh9f0ad1d_0    conda-forge
dash-core-components      1.12.1             pyh9f0ad1d_0    conda-forge
dash-html-components      1.1.1              pyh9f0ad1d_0    conda-forge
dash-renderer             1.8.2              pyh9f0ad1d_0    conda-forge
dash-table                4.10.1             pyh9f0ad1d_0    conda-forge
dask                      2.29.0                     py_0    conda-forge
dask-core                 2.29.0                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.2              pyh9f0ad1d_0    conda-forge
distributed               2.29.0           py37hc8dfbb8_0    conda-forge
doctr                     1.8.0                      py_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
dynamicisttoolkit         0.5.3                      py_2    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastcache                 1.1.0            py37h8f50634_1    conda-forge
feedgenerator             1.9.1                      py_0    conda-forge
feedparser                5.2.1              pyh9f0ad1d_0    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
filterpy                  1.4.5                      py_1    conda-forge
flake8                    3.8.4                      py_0    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
flask-compress            1.6.0              pyh9f0ad1d_0    conda-forge
fontconfig                2.13.1            h1056068_1002    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fsspec                    0.8.3                      py_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gf2x                      1.1                           0    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.9                      py_0    conda-forge
glib                      2.66.1               h680cd38_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
go2                       2.20170703       py37hc8dfbb8_1    conda-forge
gobject-introspection     1.66.1           py37h619baee_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2020.5.30        py37hda6ee5b_2    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        2.0.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        2.0.0                         0    conda-forge
iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipopt                     3.13.2               hc6e8484_0    conda-forge
ipydatawidgets            4.1.0              pyh9f0ad1d_0    conda-forge
ipykernel                 5.3.4            py37h43977f1_0    conda-forge
ipympl                    0.5.8              pyh9f0ad1d_0    conda-forge
ipyparallel               6.3.0            py37hc8dfbb8_0    conda-forge
ipython                   7.18.1           py37hc6149b9_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
isort                     5.5.4            py37hc8dfbb8_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jedi                      0.17.1           py37hc8dfbb8_0    conda-forge
jeepney                   0.4.3                      py_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyter_sphinx            0.3.1            py37hc8dfbb8_0    conda-forge
jupyterlab                2.2.8                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
jxrlib                    1.1                  h516909a_2    conda-forge
keyring                   21.4.0           py37hc8dfbb8_1    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lazy-object-proxy         1.4.3            py37h8f50634_2    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
lerc                      2.2                  he1b5a44_0    conda-forge
libaec                    1.0.4                he1b5a44_1    conda-forge
libarchive                3.3.3             hddc7a2b_1008    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  10.0.1          default_hde54327_1    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_2    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libflint                  2.5.2                heb735ee_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblief                   0.10.1               he1b5a44_1    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libpq                     12.3                 h5513abc_0    conda-forge
libsodium                 1.0.18               h516909a_1    conda-forge
libsolv                   0.7.15               h8b12597_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
libzopfli                 1.0.3                he1b5a44_0    conda-forge
llvmlite                  0.34.0           py37h5202443_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.5.3            py37he97bff5_0    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py37hd478181_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
metakernel                0.27.0             pyh9f0ad1d_0    conda-forge
metis                     5.1.0             he1b5a44_1006    conda-forge
mistune                   0.8.4           py37h8f50634_1001    conda-forge
mock                      4.0.2            py37hc8dfbb8_0    conda-forge
more-itertools            8.5.0                      py_0    conda-forge
mpc                       1.1.0             h04dde30_1009    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            1.0.0            py37h99015e2_1    conda-forge
mysql-common              8.0.21                        2    conda-forge
mysql-libs                8.0.21               hf3661c5_2    conda-forge
nbclient                  0.5.0                      py_0    conda-forge
nbconvert                 6.0.7            py37hc8dfbb8_0    conda-forge
nbdime                    2.1.0                      py_0    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
nest-asyncio              1.4.1                      py_0    conda-forge
networkx                  2.5                        py_0    conda-forge
nose                      1.3.7           py37hc8dfbb8_1004    conda-forge
notebook                  6.1.4            py37hc8dfbb8_0    conda-forge
nspr                      4.29                 he1b5a44_0    conda-forge
nss                       3.57                 he751ad9_0    conda-forge
ntl                       10.3.0                        1    conda-forge
numba                     0.51.2           py37h9fdb41a_0    conda-forge
numexpr                   2.7.1            py37h0da4684_1    conda-forge
numpy                     1.19.1           py37h7ea13bd_2    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
oct2py                    5.2.0              pyh9f0ad1d_0    conda-forge
octave_kernel             0.32.0             pyh9f0ad1d_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.2            py37h3340039_0    conda-forge
pandoc                    2.10.1               h516909a_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pathlib                   1.0.1            py37hc8dfbb8_2    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pelican                   4.5.0              pyh9f0ad1d_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.2.0            py37h718be6c_1    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
plotly                    4.11.0             pyh9f0ad1d_0    conda-forge
pluggy                    0.13.1           py37hc8dfbb8_2    conda-forge
portalocker               1.7.0            py37hc8dfbb8_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.7                      py_0    conda-forge
prompt_toolkit            3.0.7                         0    conda-forge
psutil                    5.7.2            py37h8f50634_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
py-lief                   0.10.1           py37h3340039_1    conda-forge
pycairo                   1.19.1           py37h01af8b0_3    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py37h8f50634_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                5.1.1                      py_0    conda-forge
pydy                      0.5.0                 py37_1003    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pygobject                 3.38.0           py37hfc86313_0    conda-forge
pyinstrument              3.2.0              pyh9f0ad1d_0    conda-forge
pyinstrument_cext         0.2.2            py37h516909a_0    conda-forge
pylint                    2.6.0            py37hc8dfbb8_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h8685d9f_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3           py37h8f50634_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytables                  3.6.1            py37h56451d4_2    conda-forge
pytest                    6.1.1            py37hc8dfbb8_0    conda-forge
pytest-cov                2.10.1             pyh9f0ad1d_0    conda-forge
python                    3.7.8           h6f2ec95_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.35.1                     py_0    conda-forge
python-libarchive-c       2.9              py37hc8dfbb8_1    conda-forge
python-symengine          0.6.1            py37hd42a662_1    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pythreejs                 2.2.0              pyh8c360ce_0    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywavelets                1.1.1            py37h161383b_2    conda-forge
pyxdg                     0.26                       py_0    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
pyzmq                     19.0.2           py37hac76be4_1    conda-forge
pyzotero                  1.4.18             pyh9f0ad1d_1    conda-forge
qdarkstyle                2.8.1              pyh9f0ad1d_1    conda-forge
qt                        5.12.9               h1f2b2cb_0    conda-forge
qtawesome                 1.0.1              pyh9f0ad1d_0    conda-forge
qtconsole                 4.7.7              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
readme_renderer           26.0               pyh9f0ad1d_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
resonance                 0.22.0           py37hc8dfbb8_1    conda-forge
restview                  2.9.2              pyh9f0ad1d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rfc3986                   1.4.0              pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h516909a_0    conda-forge
rope                      0.17.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py37h8526d28_1    conda-forge
ruamel_yaml               0.15.80         py37h8f50634_1002    conda-forge
scikit-image              0.17.2           py37h9fdb41a_2    conda-forge
scikit-learn              0.23.2           py37h6785257_0    conda-forge
scipy                     1.5.2            py37hb14ef9d_0    conda-forge
seaborn                   0.11.0                        0    conda-forge
seaborn-base              0.11.0                     py_0    conda-forge
secretstorage             3.1.2            py37hc8dfbb8_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37hc8dfbb8_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
skijumpdesign             1.3.0                      py_1    conda-forge
slycot                    0.4.0.0          py37h27181d0_1    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
snakeviz                  2.1.0              pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sphinx                    3.2.1                      py_0    conda-forge
sphinx-math-dollar        1.2                pyh9f0ad1d_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.1.5            py37hc8dfbb8_0    conda-forge
spyder-kernels            1.9.4            py37hc8dfbb8_0    conda-forge
sqlite                    3.33.0               h4cf870e_0    conda-forge
statsmodels               0.12.0           py37h8f50634_0    conda-forge
symengine                 0.6.0                h9603a25_0    conda-forge
sympy                     1.6.2            py37hc8dfbb8_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.1            py37hc8dfbb8_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2020.10.1                  py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.50.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
tree                      1.8.0                h516909a_1    conda-forge
twine                     3.2.0            py37hc8dfbb8_0    conda-forge
typed-ast                 1.4.1            py37h516909a_0    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
ujson                     3.2.0            py37h3340039_0    conda-forge
uncertainties             3.1.4                      py_0    conda-forge
unidecode                 1.1.1                      py_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
watchdog                  0.10.3           py37hc8dfbb8_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py37hc8dfbb8_1    conda-forge
wrapt                     1.11.2           py37h8f50634_0    conda-forge
wurlitzer                 2.0.0            py37hc8dfbb8_1    conda-forge
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
yeadon                    1.3.0           py37hc8dfbb8_1002    conda-forge
zeromq                    4.3.3                he1b5a44_2    conda-forge
zfp                       0.5.5                he1b5a44_2    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.3.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : None
       user config file : /home/moorepants/.condarc
 populated config files : /home/moorepants/.condarc
          conda version : 4.8.5
    conda-build version : 3.20.3
         python version : 3.7.8.final.0
       virtual packages : __glibc=2.31
       base environment : /home/moorepants/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/pydy/linux-64
                          https://conda.anaconda.org/pydy/noarch
                          https://conda.anaconda.org/moorepants/linux-64
                          https://conda.anaconda.org/moorepants/noarch
          package cache : /home/moorepants/miniconda/pkgs
                          /home/moorepants/.conda/pkgs
       envs directories : /home/moorepants/miniconda/envs
                          /home/moorepants/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.8 Linux/5.4.0-48-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : /home/moorepants/.netrc
           offline mode : False

```
</details>

### PR DESCRIPTION
**Pull request by moorepants**
Fixes #84

This manually installs the Plotly JupyterLab extension as per the
instructions here:

https://conda-forge.org/docs/maintainer/knowledge_base.html#jupyterlab-extensions

If the user has JupyterLab installed in the same conda environment as
plotly, the extension will be built by JupyterLab the next time it is
opened and be available for use. Node and JupyterLab are listed in the
run_constrained section so that these packages are not hard dependencies
of the Plotly conda package.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chohner** [comment]
Were you able to verify that the resulting package fixes the jupyterlab extension?

**Comment by moorepants** [comment]
I'd have to build it locally and install that local version, so no. I can add a test to make sure the files are put in the right place if that helps.

**Comment by moorepants** [comment]
I built and installed locally and the tar ball is where it is supposed to be but when I opened Jupyterlab it didn't automatically build the extension as the conda forge documentation suggests.

```
plotly-jupy-test) moorepants@nandi:~$ tree /home/moorepants/miniconda/envs/plotly-jupy-test/share/jupyter/
/home/moorepants/miniconda/envs/plotly-jupy-test/share/jupyter/
├── kernels
│   └── python3
│       ├── kernel.json
│       ├── logo-32x32.png
│       └── logo-64x64.png
├── lab
│   ├── extensions
│   │   └── js
│   │       └── jupyterlab-plotly-4.11.0.tgz
│   ├── schemas
│   │   └── @jupyterlab
│   │       ├── application-extension
│   │       │   ├── main.json
│   │       │   ├── package.json.orig
│   │       │   └── sidebar.json
│   │       ├── apputils-extension
│   │       │   ├── package.json.orig
│   │       │   ├── palette.json
│   │       │   ├── print.json
```

**Comment by chohner** [comment]
Thanks for looking into this, seems a bit more involved than expected!
I'm not using jupyterlab so I can't be of much help I'm afraid.

My 2c from skimming the other thread: I'd rather not have additional hard dependencies if it can be avoided. But I don't have any good intuitions on what the right call is

**Comment by ocefpaf** [comment]
> My 2c from skimming the other thread: I'd rather not have additional hard dependencies if it can be avoided. But I don't have any good intuitions on what the right call is

Agreed. We can do a plotly-extras packages that brings these but that does not model to the original package publishing at all b/c the jupyterlab extension does not seem to be an optional dependency of plotly. (I may be wrong but I could not find any mentioned to it in the package metadata.)

**Comment by moorepants** [comment]
There are no hard dependencies added in this PR.

From a user's perspective, I think it would be more intuitive that "conda install jupyterlab plotly" results in a functioning environment than having to do "conda install jupyterlab plotly plotly-extras". As far as I can tell, the only cost is that the plotly binary is a bit larger because the extension is bundled in. But either is fine if it will solve the issue of having to run "jupyter labextention" and "jupyter build" commands after the conda commands. conda is suppose to be able to manage *any* packages, so it is unintuitive and hard to realize that another package management process is needed for these extensions.

**Comment by chohner** [comment]
> There are no hard dependencies added in this PR.
Not in this PR, just the other thread mentioned a dependency as one solution.

I don't think anyone is going to complain about a slightly larger package here. Actually - do you know how much larger the package will get?

But going from your assessment, the current state also doesn't really solve the issue, right?

**Comment by moorepants** [comment]
> But going from your assessment, the current state also doesn't really solve the issue, right?

This PR does not currently work as the Conda Forge docs imply. I'm waiting on feedback from others in another thread as to why.

**Comment by moorepants** [comment]
Closing this, as JupyterLab 3.0 introduces a new way to package and install extensions as Python packages.

**Pull request closed without merging**
