### PR TITLE
update to 2.0.0

### PR DESCRIPTION
**Pull request by chohner**

### CODE REVIEW

**Comment by jakirkham** [comment]
May also be a good time to [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ). We are on `conda-smithy` 2.0.1 now.

**Comment by chohner** [comment]
Just checked and I am getting a `maximum recursion depth exceeded` when re-rendering with 2.0.1

**Comment by jakirkham** [comment]
Could you please share some details?

**Comment by chohner** [comment]
The first run of the `conda smithy rerender` added a LICENSE file but then hanged at `Fetching package metadata ...........` for a bit and then just returns wirht `maximum recursion depth exceeded`.

**Comment by jakirkham** [comment]
Sorry I should have been more specific. What are the result of `conda info`, `conda list -n root`, etc.?

**Comment by chohner** [comment]
oh sure!
```
conda-info:

Current conda install:

               platform : osx-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.1.2
         python version : 3.5.3.final.0
       requests version : 2.12.5
       root environment : /Users/USER/miniconda3  (writable)
    default environment : /Users/USER/miniconda3
       envs directories : /Users/USER/miniconda3/envs
          package cache : /Users/USER/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /Users/USER/.condarc
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.5 CPython/3.5.3 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
```

I just ran `conda install conda-smithy --force` and now I get an `AssertionError` when re-rendering:

```
Fetching package metadata ...........
Traceback (most recent call last):
  File "/Users/USER/miniconda3/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 200, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 644, in main
    render_run_docker_build(env, config, forge_dir)
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 77, in render_run_docker_build
    forge_config.get('channels', {}).get('sources', tuple())
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 566, in compute_build_matrix
    mtx = list(filter_cases(mtx, ['python >=2.7,<3|>=3.5', 'numpy >=1.11']))
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_build_all/version_matrix.py", line 272, in filter_cases
    match.append(bool(spec.match(cases_by_pkg_name[spec.name])))
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 105, in match
    assert isinstance(dist, Dist)
AssertionError
```


I'll do some cleanup on my end to see whether that fixes my problem.

**Comment by chohner** [comment]
I just did a clean reinstall:
```
Current conda install:

               platform : osx-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.2
         python version : 3.5.3.final.0
       requests version : 2.12.5
       root environment : /Users/USER/miniconda3  (writable)
    default environment : /Users/USER/miniconda3
       envs directories : /Users/USER/miniconda3/envs
          package cache : /Users/USER/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /Users/chohner/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.5 CPython/3.5.3 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
```

and `conda smithy rerender` now throws a different error:

```
conda smithy rerender
Fetching package metadata ...........
Traceback (most recent call last):
  File "/Users/USER/miniconda3/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 200, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 644, in main
    render_run_docker_build(env, config, forge_dir)
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 77, in render_run_docker_build
    forge_config.get('channels', {}).get('sources', tuple())
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 565, in compute_build_matrix
    mtx = special_case_version_matrix(meta, index)
  File "/Users/USER/miniconda3/lib/python3.5/site-packages/conda_build_all/version_matrix.py", line 212, in special_case_version_matrix
    py_vn = minor_vn(index[python_pkg.fn]['version'])
AttributeError: 'Dist' object has no attribute 'fn'

```

This is probably not the right place to talk about conda-smithy, should I move this to https://github.com/conda-forge/conda-smithy/issues?

**Comment by jakirkham** [comment]
Yeah, the last problem is `conda` 4.3 and `conda-build-all` are not compatible, which is what that issue is discussing. Downgrading to `conda` 4.2 works around the issue. Glad you were able to resolve it.

**Pull request merged**
